config/routes.rb
NACLA::Application.routes.draw do
  get "articles/show"

  match "back_url" => 'application#back_url'
  get "comments/show"
  get "comments/add"
  get "comments/delete"
  get "comments/" => "comments#index"
  post "comments/add"
  post "comments/delete" => "comments#delete"
  match "comments/create_comment" => "comments#create_comment"

  match 'articles/search' => 'articles#search'
  match 'articles/:id/download' => 'articles#download'
  match 'articles/:id' => 'articles#show'

  post 'new/list_all' => 'course_packs#list_all'
  post 'course_packs/new' => 'course_packs#add_article'
  match 'course_packs/create' => 'course_packs#create'
  get 'course_packs/all_articles' => 'course_packs#all_articles'
  match 'course_packs/search' => 'course_packs#search'
  post 'course_packs/update' => 'course_packs#update'

  resources :course_packs
  get 'user/usernames'=>'users#usernames'
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "log_in" => "sessions#create" 
  get "sign_up" => "users#new", :as => "sign_up"
  get "edit_user" => "users#edit", :as => "edit_user"
  post "edit_user" => "users#update"
  post "destroy_user/:id" => "users#destroy"
  match "user/profile" => "users#index"
  resources :users

  match "search" => "articles#search"

  match 'home', :to => "static#index"
  root :to => "static#index"

  match ':controller(/:action(/:id))(.:format)'
  match "*path" => redirect('/')
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password

  has_many :course_packs
  has_many :comments


  validates_confirmation_of :password
  validates_presence_of :password
  validates_presence_of :email, :on => :create
  validates_presence_of :username, :on => :create
  validates_uniqueness_of :email
  validates_uniqueness_of :username

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.get_names

    user_names = {}

    User.all.each do |user|
      user_names[user.id] = user.username
    end

    return user_names

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_login, except: [:new, :create, :usernames]
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
   
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), :notice=>"You have created an account."
    else
      render "new"
    end
  end

  def update
    if params[:commit] == "Cancel"
      redirect_to '/users'
    else
      user = User.authenticate(current_user.username, params[:old_password])
      if user != nil
        if params[:password] == params[:password_confirmation]
          change_user_password(user)
        else
          flash[:notice] = "Password doesn't match confirmation"
          render "edit"
        end
      else
        flash[:notice] = 'Your password is incorrect'
        render "edit"
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @coursepacks = CoursePack.find_all_by_user_id(@user[:id], :order => "created_at desc", :limit =>5) || []
    @comments = Comment.find_all_by_user_id(@user.id, :order => "created_at desc", :limit => 10) || []
    @coursepacks = trim(@coursepacks)
    @comments = trim(@comments)
  end
  
  def index
    redirect_to user_path(current_user[:id])
  end

  def destroy
    userid = params[:id]
    if !prevent_admin_delete(userid)
      if userid == current_user.id.to_s or current_user.admin
        user = User.find(userid)
        delete_user(user)
        redirect_after_user_delete(user)
      else
        redirect_to user_path(current_user.id), :notice => "You don't have permission to do that"
      end
    end
  end

  def usernames
    if request.xhr?
      render json: User.get_names.to_json, :status=>:ok
    else
      redirect_to '/'
    end

  end
  
  private

  def record_not_found
    redirect_to '/log_out', :notice => "You were logged out for accessing a non-existant account"
  end

  def delete_user(user)
    coursepacks = user.course_packs
    coursepacks.each do |coursepack|
      comments = coursepack.comments
      comments.each do |comment|
        comment.destroy
      end
      coursepack.destroy
    end
    comments = user.comments
    comments.each do |comment|
      comment.destroy
    end
  end

  def prevent_admin_delete(userid)
    if current_user.admin and User.where(admin: true).size <= 1 and current_user.id.to_s == userid
      redirect_to user_path(current_user.id), :notice => "You are the last admin. You can't delete your profile"
      return true
    else
      return false
    end
  end
  
  def redirect_after_user_delete(user)
    if current_user.id.to_s == user.id
      session[:user_id] = nil
      user.destroy
      redirect_to '', :notice => "Your account was deleted"
    else
      message = user.username + "'s account was deleted"
      user.destroy
      redirect_to user_path(current_user.id), :notice => message
    end
  end

  def change_user_password(user)
    if user.id == current_user.id 
      user.password = params[:password]
      if user.save
        redirect_to '', :notice=>"Your password has been changed."
      else
        flash[:notice] = "Your new password is not valid. Please enter another"
        render "edit"
      end
    else
      flash[:notice] = "You shouldn't be here..."
      render "edit"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_tag "edit_user" do |f| %>
  <p>
    <%= label_tag :old_password %>
    <%= password_field_tag :old_password %>
  </p>
  <p>
    <%= label_tag :new_password %>
    <%= password_field_tag :password %>
  </p>
  <p>
    <%= label_tag :password_confirmation %>
    <%= password_field_tag :password_confirmation %>
  </p>
  <%= submit_tag 'Change Password' %>
  <%= submit_tag 'Cancel' %>
<% end %>

app/views/users/index.html.erb
<h1><%=@user[:username]%>'s Profile</h1>

<%= @user[:id] %>

<p><%= link_to 'Change Password', edit_user_path %></p>
<p><%= link_to 'Delete Profile', destroy_user_path, :confirm => "Are you sure you want to delete your profile?" %></p>

<div>
  <b>Recent Course Packs</b>
  <% @coursepacks.each do |coursepack| %>
    <p>
      <%= coursepack.title %>
      <%= link_to 'Show', course_pack_path(coursepack[:id]) %>
      <%= link_to 'Edit', edit_course_pack_path(coursepack[:id]) %>
    </p>
  <% end %>
  <p><%= link_to 'Click Here For More Course Packs', course_packs_path %> </p>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <% for message in @user.errors.full_messages %>
      <%= message %>
    <% end %>
  <% end %>
  <p>
  <%= f.label :username %>
  <%= f.text_field :username %>
  </p>
  <p>
  <%= f.label :email %>
  <%= f.text_field :email%>
  </p>
  <p>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </p>
  <p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit 'Create new account' %>
<% end %>

app/views/users/show.html.erb
<div id='profile'>

  <div id = 'profile_header'>
    <h2>Welcome, <%=@user.username%>!</h2> 
  </div>
    
  <div id = 'edit_container'>
    <% if @user.username == current_user.username %>
      <div class='edit_profile'><%= button_to 'Change Password', edit_user_path, class:'edit_profile_button' %></div>
    <% end %>
    <% if @user.username == current_user.username or current_user.admin %>
      <div class='edit_profile'><%= button_to 'Delete Profile', '/destroy_user/'+@user.id.to_s, 
        :confirm => "Are you sure you want to delete this profile?", class:'edit_profile_button'%></div>
    <% end %>
  </div>
  <br> <br> <br> 
  <hr class='dotted'>
  
  <div id = 'profile_course_packs'>
    <b id = 'profile_course_packs_header'><%= @user.username %>'s Recent Course Packs</b> 
    <%= button_to 'Click Here For More Course Packs', course_packs_path, method: :get, class:'more_button' %>
    <br> <br>
    <% if @coursepacks.empty? %>
      <p class='empty'>You don't have any coursepacks yet! 
        <!--<%= link_to "Why don't you click here to create one?", new_course_pack_path, id:'new_link' %></p>-->
      
    <% end %>
    <% @coursepacks.each do |course_pack| %>
      <div class='course_pack_show'>
        <a class="<%=course_pack.title%>" id='show_link' href="javascript:save_back('<%="/users/#{@user.id}"%>','<%="/course_packs/#{course_pack.id}"%>')">
        <div>
          <div class='course_pack_headers'><%= course_pack.title %></div>
          <div class='course_pack_content'><%= course_pack.summary %></div>
          <br>  
        </div>
        </a>
        <%= button_to "Edit", edit_course_pack_path(course_pack[:id]), method: :get, id:'edit_course_pack'%>
        <%= button_to "Destroy", course_pack,method: :delete,data:{confirm: "Are you sure?"}, id:'course_pack_destroy'%>
      </div>
    <% end %>  
  </div>  
  <hr class='dotted'>
  <div id = 'profile_comments'>

    <b id = 'profile_comments_header'> <%= @user.username %>'s Recent Comments </b>
    <%= button_to 'Click Here For More Comments', comments_path, method: :get, class:'more_button' %>
    <br>
    <% if @comments.empty? %>
      <p class='empty'>You haven't written any comments yet! </p>      
    <% end %>
    <% @comments.each do |comment| %>
      <div class='comment_show'>
        <% commentPack = CoursePack.find(comment.course_pack_id) %>
        <a href="<%="/course_packs/#{commentPack.id}"%>" class='show_link', id='show_link'>
        <div>
          <div class='comment_header'><%= commentPack.title %></b></div>
          <div class='comment_content'><%= comment.comment %></div>
        </div>
        </a>
      </div>
    <% end %>
    <br>

  </div>
  
</div>