config/routes.rb
NACLA::Application.routes.draw do
  get "articles/show"

  match "back_url" => 'application#back_url'
  get "comments/show"
  get "comments/add"
  get "comments/delete"
  get "comments/" => "comments#index"
  post "comments/add"
  post "comments/delete" => "comments#delete"
  match "comments/create_comment" => "comments#create_comment"

  match 'articles/search' => 'articles#search'
  match 'articles/:id/download' => 'articles#download'
  match 'articles/:id' => 'articles#show'

  post 'new/list_all' => 'course_packs#list_all'
  post 'course_packs/new' => 'course_packs#add_article'
  match 'course_packs/create' => 'course_packs#create'
  get 'course_packs/all_articles' => 'course_packs#all_articles'
  match 'course_packs/search' => 'course_packs#search'
  post 'course_packs/update' => 'course_packs#update'

  resources :course_packs
  get 'user/usernames'=>'users#usernames'
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  post "log_in" => "sessions#create" 
  get "sign_up" => "users#new", :as => "sign_up"
  get "edit_user" => "users#edit", :as => "edit_user"
  post "edit_user" => "users#update"
  post "destroy_user/:id" => "users#destroy"
  match "user/profile" => "users#index"
  resources :users

  match "search" => "articles#search"

  match 'home', :to => "static#index"
  root :to => "static#index"

  match ':controller(/:action(/:id))(.:format)'
  match "*path" => redirect('/')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="NACLA">

<head>
  <title> NACLA </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>

  <%#= javascript_include_tag "jquery.sticky" %>
  <%= csrf_meta_tags %>
  <script>
  	$(document).ready(function(){
    	//$("#shadow_bar").sticky({topSpacing:40});
    	$('.menu_link').css("visibility", "hidden");
		$('.dropdown-toggle').dropdown();
		  var width = $(window).width();
		  $('#test').hover(function() {
		        $("#menu_bar").css("height", "30px");
				$('.menu_link').css("visibility", "visible");
		    }, function() {
		        $("#menu_bar").css("height", "0px");
	    		$('.menu_link').css("visibility", "hidden");
		    });

//		var leftHeight = $("#left_content").height();
//		var centerHeight = $("#center_content").height();
//		var rightHeight = $("#right_content").height();
//		var centerWidth = $("#content_container").width()*.7 - 11;
//		$("#center_content").css("width", centerWidth);
//		if(leftHeight > centerHeight || rightHeight > centerHeight)
//		{
//			if(leftHeight > rightHeight)
//			{
//				$("#center_content").css("height", leftHeight);
//			}
//			else
//			{
//				$("#center_content").css("height", rightHeight);
//			}
//		}
	});
  </script>
</head>
<body style ="margin:0px; min-width: 990px;">
   <div id="container">

		<div id="content_container">
			<div id="logo_container">
				<div id="top_links_container">
					<span style="display:table; float:center; margin-left:auto; margin-right:auto;">
					<p class="top_link">ADVERTISE</p>
					<p class="top_link">SUBSCRIBE</p>
					<p class="top_link">STORE</p>
					<p class="top_link">MY CART</p>
					<p class="top_link">CLACS at NYU</p>
					<p class="top_link" style="border-right-width:0px;">ARCHIVE OF LATIN AMERICA</p>
					</span>
				</div>
				<img style="width:700px; display: block; margin-bottom:10px; margin-top:10px; margin-left:auto; margin-right:auto;" src="/images/nacla_logo.jpg">
				<div id="links_bar">
					<div class="links_item">

						<%= link_to 'HOME', root_path, :class =>"links_item_text" %>
					</div>
					<div class="links_item">
						<%= link_to 'COURSE PACKS', course_packs_path, :class =>"links_item_text" %>
					</div>
					<div class="links_item">
						<%= link_to 'SEARCH', {:controller=>"search", :action => "index"}, :class =>"links_item_text" %>
					</div>
					<div class="links_item">
					  <%= link_to 'PROFILE', users_path, :class =>"links_item_text" %>
					</div>
					<div class="links_item">
					  <%= link_to 'COMMENTS', comments_path, :class =>"links_item_text" %>
					</div>
				</div>
			</div>
			<div>
				<div id="left_content">
					<div class="left_ad">
						<p class="left_ad_text">Subscribe to NACLA Report today!</p>
					</div>

					<div id="news_container_header" class="left_container_div">
						<p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px;">NACLA News</p>
					</div>
					<div id="news_container" class="left_container_div">
						<p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px;"></p>
					</div>

					<div id="left_login_container" class="left_container_div">
						<p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px;">NACLA User Login</p>						
						<% if current_user %>
							<p>Logged in as <%= current_user.username %> </p>
							<p><%= link_to "Your profile", "/users" %></p>
							<p><%= link_to "Log out", log_out_path %></p>
						<% else %>						
							<%= form_tag "/log_in" do %>
	                       			 		<div class='login_div'><%= text_field_tag :username, params[:username], id: "username", placeholder: "Username" %>        </div>
                                            <div class='login_div'><%= password_field_tag :password, params[:password], id: "password", placeholder: "Password" %>    </div>
                       				 		<button class="btn" id="left_signin_submit" type="submit">Sign In</button>
                        				<% end %>
				                        <p style="text-align:center; color:navy; font-size:10px; font-weight: bold; line-height:15px; margin-top:-18px;"><%= link_to "Register for an account", sign_up_path%></p>
						<% end %>
					</div>

					<div class="left_white_container_div">
						<p style="text-align:center; color:orange; font-size:10px; font-weight: bold; line-height:15px; margin-top:-18px;">SEARCH</p>
						<%= form_tag("/search", method: "get") do %>
						    <%= text_field_tag :search, params[:search], id: "left_search", placeholder: "Search" %>
						    <button class="btn"type="submit" style="margin-left:auto; margin-right:auto; width:60px; margin-bottom:-15px; display:block;">
						    	<p>GO</p>
						    </button>
					  	<% end %>
					</div>

					<div class="left_white_container_div">
						<p style="text-align:center; color:orange; font-size:10px; font-weight: bold; line-height:15px; margin-top:-18px;">SIGN UP FOR OUR EMAIL LIST</p>
					</div>

					<div class="left_ad">
						<p class="left_ad_text">Visit the NACLA store</p>
					</div>
				</div>
				<div id="center_content" >
					<div id="content">
					  <div id='flash_notice'>
              <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, :id => "flash#{name}" %>
              <% end %>
            </div>
						<%= yield %>
					</div>
				</div>
				<div id="right_content">
                  <div id="featured_container_header" class="left_container_div" style="background-color:#EEEEEE; border-style: solid; border-width:1px; border-color:#EEEEEE;">
                    <p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px;">FEATURED COURSE PACKS</p>
                  </div>
                  <div id="featured_container" class="left_container_div" style="background-color:white; border-style: solid; border-width:1px; border-color:#EEEEEE">
                    <p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px; height:200px;">
                      <% @featured_course_packs.each do |featured| %>
                        <%= link_to "#{featured.title}","/course_packs/#{featured.id}" %><br/><br/>
                      <% end %>
                    </p>
                  </div>

					<div id="ads_container_header" class="left_container_div" style="background-color:#EEEEEE; border-style: solid; border-width:1px; border-color:#EEEEEE;">
						<p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px;">ADVERTISEMENT</p>
					</div>
					<div id="ads_container" class="left_container_div" style="background-color:white; border-style: solid; border-width:1px; border-color:#EEEEEE;">
						<p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px;"></p>
					</div>

					<div id="archives_container_header" class="left_container_div">
						<p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px;">NACLA Archives</p>
					</div>
					<div id="archives_container" class="left_container_div">
						<p style="text-align:center; font-size:15px; font-weight: bold; line-height:15px;"></p>
					</div>
					
				</div>
			</div>
		</div>
		<div id="push"></div>
	</div>

	<div id="footer">
		<div id="footer_container">
			<div id="footer_text_container">
				<div id="footer_column1">
					<p class="footer_text" style="margin-top:20px;">NACLA | c/o NYU CLACS</p>
					<p class="footer_text">53 WASHINGTON SQ. SOUTH FL. 4W</p>
					<p class="footer_text">NEW YORK, NY 10012</p>

					<p class="footer_text" style="margin-top:20px;">TEL: (646) 535-9085</p>
				</div>
				<div id="footer_column2">
					<p class="footer_text" style="margin-top:20px;">Sitemap</p>
					<p class="footer_text">Terms Of Use</p>
					<p class="footer_text">Privacy Policy</p>
					<p class="footer_text">Contact Us</p>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield